name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: ["gateway", "info", "logging"]
    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      working-directory: ./${{ matrix.path }}
      run: go build -v ./...

    #- name: Test
    #  run: go test -v ./...
    
  typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.1
      with:
        node-version: 14.x
        cache: yarn
        
    - name: Install Dependencies
      run: yarn --immutable

    - name: Build
      run: yarn build
