name: Push Docker Image

on:
    push:
        branches: ["release"]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                path: ["gateway", "info", "logging"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log in
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract Metadata
              id: meta
              uses: docker/metadata-action@v2
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.path }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  file: ${{ matrix.path }}/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
